import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'
import { ThemeProvider } from '@/components/theme-provider'
import '@/styles/globals.css'
import NavMenu from '@/components/nav-menu'
import Footer from '@/components/footer'
// import { VercelToolbar } from '@vercel/toolbar/next'

export const metadata: Metadata = {
  title: 'H3xWizz',
  description: 'Generated by create next app',
  icons: '/logo.svg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const shouldInjectToolbar = useIsUserEmployee();

  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavMenu/>
          <main className={'h-[calc(100vh-6rem)] mx-[calc(100vh-30rem)]'}>
            {children}
          </main>
          <Footer/>
          {/* {shouldInjectToolbar && <VercelToolbar />} */}
        </ThemeProvider>
      </body>
    </html>
  )
}
