import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'
import { ThemeProvider } from '@/components/theme-provider'
import '@/styles/globals.css'
import NavMenu from '@/components/nav-menu'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'H3xWizz',
  description: 'Generated by create next app',
  icons: '/logo.svg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavMenu/>
          <main className="h-full">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
